dom <- read.table('J2', header=T)
attach(dom)
pdf('Jho.pdf')
par(mfrow=c(3,2))
plot(x, type='l')
plot(y, type='l')
plot(z, type='l')
plot(Energy, type='l')
plot(a, type='l')
plot(h, type='l')
dev.off()
