d <- read.table("kep", header=T)
attach(d)
plot(x, type="l")
plot(y, type="l")
plot(z, type="l")
plot(Energy, type="l")
plot(a, type="l")
plot(h, type="l")
plot(e, type="l")
plot(OMEGA, type="l")
plot(I, type="l")
