CFLAGS = -I/usr/X11R6/include
LIBS = -L/usr/X11R6/lib -lglut -lGLU -lGL -lXmu -lXi -lXext -lX11 -lm
#a.out: prog1.cpp
#	$(CC) $(CFLAGS) prog1.cpp -o a.out $(LIBS)
#2a.out: prog2.cpp
#	$(CC) $(CFLAGS) prog2.cpp -o 2a.out $(LIBS)
3a.out: move.cpp
	$(CC) $(CFLAGS) move.cpp -o 3a.out $(LIBS)
